// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmUiZvSkZYrfWGqxH9yPZ1NbkPFKiCal8',
    appId: '1:918288525877:android:064af739af167378869f7c',
    messagingSenderId: '918288525877',
    projectId: 'thefourthoneindia-11e5f',
    databaseURL: 'https://thefourthoneindia-11e5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thefourthoneindia-11e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVqabHylrh7pf2xPyGySbMX65t_cu6bVc',
    appId: '1:918288525877:ios:704605affb17f6c8869f7c',
    messagingSenderId: '918288525877',
    projectId: 'thefourthoneindia-11e5f',
    databaseURL: 'https://thefourthoneindia-11e5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thefourthoneindia-11e5f.appspot.com',
    iosBundleId: 'com.app.theFourthOneIndia',
  );
}
